class CreateMunicipalities < ActiveRecord::Migration
  def change
    create_table :municipalities do |t|
      t.string :name

      t.timestamps null: false
    end
    execute "insert into municipalities values (nextval('municipalities_id_seq'), 'ΑΓΙΑΣ ΒΑΡΒΑΡΑΣ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΑΓΙΑΣ ΠΑΡΑΣΚΕΥΗΣ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΑΓΙΟΥ ΔΗΜΗΤΡΙΟΥ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΝΙΚΑΙΑΣ - ΑΓΙΟΥ ΙΩΑΝΝΗ ΡΕΝΤΗ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΛΑΥΡΕΩΤΙΚΗΣ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΔΙΟΝΥΣΟΥ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΑΓΙΩΝ ΑΝΑΡΓΥΡΩΝ - ΚΑΜΑΤΕΡΟΥ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΑΓΚΙΣΤΡΙΟΥ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΑΘΗΝΑΙΩΝ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΑΙΓΑΛΕΩ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΑΙΓΙΝΑΣ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΑΛΙΜΟΥ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΑΜΑΡΟΥΣΙΟΥ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΣΑΛΑΜΙΝΑΣ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΣΑΡΩΝΙΚΟΥ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΠΑΛΛΗΝΗΣ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΔΙΟΝΥΣΟΥ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΚΥΘΗΡΩΝ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΦΥΛΗΣ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΕΛΛΗΝΙΚΟΥ - ΑΡΓΥΡΟΥΠΟΛΗΣ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΣΠΑΤΩΝ - ΑΡΤΕΜΙΔΟΣ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΑΣΠΡΟΠΥΡΓΟΥ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΩΡΩΠΟΥ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΩΡΩΠΟΥ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΑΧΑΡΝΩΝ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΒΑΡΗΣ - ΒΟΥΛΑΣ - ΒΟΥΛΙΑΓΜΕΝΗΣ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΜΑΡΑΘΩΝΟΣ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΜΑΝΔΡΑΣ - ΕΙΔΥΛΛΙΑΣ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΒΑΡΗΣ - ΒΟΥΛΑΣ - ΒΟΥΛΙΑΓΜΕΝΗΣ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΒΑΡΗΣ - ΒΟΥΛΑΣ - ΒΟΥΛΙΑΓΜΕΝΗΣ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΒΡΙΛΗΣΣΙΩΝ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΒΥΡΩΝΟΣ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΓΑΛΑΤΣΙΟΥ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΠΑΛΛΗΝΗΣ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΠΑΙΑΝΙΑΣ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΓΛΥΦΑΔΑΣ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΜΑΡΑΘΩΝΟΣ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΔΑΦΝΗΣ - ΥΜΗΤΤΟΥ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΔΙΟΝΥΣΟΥ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΚΕΡΑΤΣΙΝΙΟΥ - ΔΡΑΠΕΤΣΩΝΑΣ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΔΙΟΝΥΣΟΥ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΚΗΦΙΣΙΑΣ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΕΛΕΥΣΙΝΑΣ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΕΛΛΗΝΙΚΟΥ - ΑΡΓΥΡΟΥΠΟΛΗΣ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΜΑΝΔΡΑΣ - ΕΙΔΥΛΛΙΑΣ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΦΥΛΗΣ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΖΩΓΡΑΦΟΥ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΗΛΙΟΥΠΟΛΕΩΣ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΗΡΑΚΛΕΙΟΥ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΑΧΑΡΝΩΝ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΙΛΙΟΥ (ΝΕΩΝ ΛΙΟΣΙΩΝ)', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΚΑΙΣΑΡΙΑΝΗΣ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΩΡΩΠΟΥ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΚΑΛΛΙΘΕΑΣ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΣΑΡΩΝΙΚΟΥ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΑΓΙΩΝ ΑΝΑΡΓΥΡΩΝ - ΚΑΜΑΤΕΡΟΥ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΩΡΩΠΟΥ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΛΑΥΡΕΩΤΙΚΗΣ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΚΕΡΑΤΣΙΝΙΟΥ - ΔΡΑΠΕΤΣΩΝΑΣ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΚΗΦΙΣΙΑΣ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΚΟΡΥΔΑΛΛΟΥ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΣΑΡΩΝΙΚΟΥ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΔΙΟΝΥΣΟΥ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΚΡΩΠΙΑΣ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΚΥΘΗΡΩΝ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΛΑΥΡΕΩΤΙΚΗΣ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΛΥΚΟΒΡΥΣΗΣ - ΠΕΥΚΗΣ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΕΛΕΥΣΙΝΑΣ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΩΡΩΠΟΥ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΜΑΝΔΡΑΣ - ΕΙΔΥΛΛΙΑΣ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΜΑΡΑΘΩΝΟΣ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΜΑΡΚΟΠΟΥΛΟΥ ΜΕΣΟΓΑΙΑΣ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΩΡΩΠΟΥ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΜΕΓΑΡΕΩΝ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΤΡΟΙΖΗΝΙΑΣ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΠΕΝΤΕΛΗΣ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΜΕΤΑΜΟΡΦΩΣΕΩΣ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΜΟΣΧΑΤΟΥ - ΤΑΥΡΟΥ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΚΗΦΙΣΙΑΣ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΝΕΑΣ ΙΩΝΙΑΣ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΜΑΡΑΘΩΝΟΣ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΠΕΝΤΕΛΗΣ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΜΕΓΑΡΕΩΝ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΝΕΑΣ ΣΜΥΡΝΗΣ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΦΙΛΑΔΕΛΦΕΙΑΣ - ΧΑΛΚΗΔΟΝΟΣ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΦΙΛΑΔΕΛΦΕΙΑΣ - ΧΑΛΚΗΔΟΝΟΣ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΦΙΛΟΘΕΗΣ - ΨΥΧΙΚΟΥ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΝΙΚΑΙΑΣ - ΑΓΙΟΥ ΙΩΑΝΝΗ ΡΕΝΤΗ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΜΑΝΔΡΑΣ - ΕΙΔΥΛΛΙΑΣ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΠΑΙΑΝΙΑΣ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΣΑΡΩΝΙΚΟΥ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΠΑΛΑΙΟΥ ΦΑΛΗΡΟΥ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΠΑΛΛΗΝΗΣ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΠΑΠΑΓΟΥ - ΧΟΛΑΡΓΟΥ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΠΕΙΡΑΙΩΣ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΠΕΝΤΕΛΗΣ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΠΕΡΑΜΑΤΟΣ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΠΕΡΙΣΤΕΡΙΟΥ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΠΕΤΡΟΥΠΟΛΕΩΣ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΛΥΚΟΒΡΥΣΗΣ - ΠΕΥΚΗΣ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΡΑΦΗΝΑΣ - ΠΙΚΕΡΜΙΟΥ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΩΡΩΠΟΥ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΠΟΡΟΥ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΡΑΦΗΝΑΣ - ΠΙΚΕΡΜΙΟΥ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΔΙΟΝΥΣΟΥ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΣΑΛΑΜΙΝΑΣ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΣΑΡΩΝΙΚΟΥ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΣΠΑΤΩΝ - ΑΡΤΕΜΙΔΟΣ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΣΠΕΤΣΩΝ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΔΙΟΝΥΣΟΥ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΩΡΩΠΟΥ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΜΟΣΧΑΤΟΥ - ΤΑΥΡΟΥ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΤΡΟΙΖΗΝΙΑΣ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΥΔΡΑΣ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΔΑΦΝΗΣ - ΥΜΗΤΤΟΥ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΦΙΛΟΘΕΗΣ - ΨΥΧΙΚΟΥ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΦΥΛΗΣ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΧΑΙΔΑΡΙΟΥ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΧΑΛΑΝΔΡΙΟΥ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΠΑΠΑΓΟΥ - ΧΟΛΑΡΓΟΥ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΦΙΛΟΘΕΗΣ - ΨΥΧΙΚΟΥ', now(), now());
insert into municipalities values (nextval('municipalities_id_seq'), 'ΩΡΩΠΟΥ', now(), now());";
  end
end
