class CreateBusRoutes < ActiveRecord::Migration
  def change
    create_table :bus_routes do |t|
      t.string :name

      t.timestamps null: false
    end
    execute "insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΣΥΝΤΑΓΜΑ - ΒΟΥΛΑ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΑΝΘΟΥΠΟΛΗ - ΣΤ.ΕΛΛΗΝΙΚΟ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΑΙΓΑΛΕΩ - ΔΟΥΚ. ΠΛΑΚΕΝΤΙΑΣ - ΑΕΡΟΔΡΟΜΙΟ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΜΑΓΟΥΛΑ(ΚΙΑΤΟ)-ΑΝΩ ΛΙΟΣΙΑ - ΑΕΡΟΔΡΟΜΙΟ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΠΕΙΡΑΙΑΣ - ΚΗΦΙΣΙΑ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΠΛΑΤ. ΑΤΤΙΚΗΣ - ΤΖΙΤΖΙΦΙΕΣ - ΜΟΣΧΑΤΟ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΑΝΩ ΚΥΨΕΛΗ - ΠΑΓΚΡΑΤΙ - ΚΑΙΣΑΡΙΑΝΗ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'Ν. ΦΙΛΑΔΕΛΦΕΙΑ - ΑΝΩ ΠΑΤΗΣΙΑ - ΓΗΡΟΚΟΜΕΙΟ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΑΝΩ ΚΥΨΕΛΗ - ΑΓ. ΑΡΤΕΜΙΟΣ - ΣΤ. ΜΕΤΡΟ ΑΓ. ΙΩΑΝΝΗΣ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΛΑΜΠΡΙΝΗ - ΠΛ. ΣΥΝΤΑΓΜΑΤΟΣ - ΤΖΙΤΖΙΦΙΕΣ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΙΠΠΟΚΡΑΤΟΥΣ - Ν. ΦΙΛΑΔΕΛΦΕΙΑ - ΚΟΚ. ΜΥΛΟΣ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΤΖΙΤΖΙΦΙΕΣ - ΧΑΛΑΝΔΡΙ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'Α. ΠΑΤΗΣΙΑ - Ν. ΠΑΓΚΡΑΤΙ - Ν. ΕΛΒΕΤΙΑ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΖΑΠΠΕΙΟ - ΠΕΡΙΣΤΕΡΙ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΛΑΜΠΡΙΝΗ - ΠΛ. ΚΑΝΙΓΓΟΣ - Ν. ΨΥΧΙΚΟ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΠΛ. ΠΑΠΑΔΙΑΜΑΝΤΗ - Λ. ΑΛΕΞΑΝΔΡΑΣ - ΓΗΡΟΚΟΜΕΙΟ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΠΕΤΡΑΛΩΝΑ - ΔΙΚΑΣΤΗΡΙΑ - ΕΛ. ΒΕΝΙΖΕΛΟΥ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΑΓ. ΙΩΑΝΝΗΣ ΡΕΝΤΗΣ - ΠΕΙΡΑΙΑΣ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΠΕΙΡΑΙΑΣ - ΑΓ. ΓΕΩΡΓΙΟΣ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΜΟΥΣΕΙΟ - ΧΑΛΑΝΔΡΙ (ΕΘΝ. ΑΝΤΙΣΤΑΣΕΩΣ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΜΟΥΣΕΙΟ - ΣΤ. ΧΑΛΑΝΔΡΙΟΥ (ΣΙΔΕΡΑ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'Ν. ΦΑΛΗΡΟ - ΚΑΣΤΕΛΛΑ - ΔΡΑΠΕΤΣΩΝΑ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΝΙΚΑΙΑ - Π. ΡΑΛΛΗ - ΟΜΟΝΟΙΑ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΠΕΤΡΟΥΠΟΛΗ - ΙΛΙΟΝ - ΣΤ. ΑΓ. ΑΝΤΩΝΙΟΣ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΚΑΜΑΤΕΡΟ - ΙΛΙΟΝ - ΣΤ. ΑΓ. ΑΝΤΩΝΙΟΣ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΚΑΝΙΓΓΟΣ - ΓΚΥΖΗ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'Ν. ΚΥΨΕΛΗ - ΜΑΡΑΣΛΕΙΟΣ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΑΓ. ΑΝΑΡΓΥΡΟΙ-ΣΤ. ΑΤΤΙΚΗΣ-ΣΤ. ΛΑΡΙΣΗΣ (ΚΥΚΛΙΚΗ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΙΠΠΟΚΡΑΤΟΥΣ - ΠΡΟΦ. ΔΑΝΙΗΛ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΙΠΠΟΚΡΑΤΟΥΣ - ΒΟΤΑΝΙΚΟΣ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΙΠΠΟΚΡΑΤΟΥΣ - ΟΡΦΕΩΣ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΑΝΩ ΚΥΨΕΛΗ - ΠΕΤΡΑΛΩΝΑ - ΤΑΥΡΟΣ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΣΤ.ΚΑΤΕΧΑΚΗ-ΣΤ.ΠΑΝΟΡΜΟΥ-ΓΑΛΑΤΣΙ-ΚΥΨΕΛΗ (ΚΥΚΛ.)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΠΕΙΡΑΙΑΣ - ΣΥΝΤΑΓΜΑ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΜΟΥΣΕΙΟ - ΕΛΛΗΝΟΡΩΣΩΝ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΠΕΙΡΑΙΑΣ - ΟΜΟΝΟΙΑ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΟΜΟΝΟΙΑ - ΣΤΑΘ. ΥΠΕΡ. ΛΕΩΦ. ΚΗΦΙΣΟΥ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΠΕΡΙΣΣΟΣ - ΑΚΑΔΗΜΙΑ - ΜΕΤΑΜΟΡΦΩΣΗ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΟΜΟΝΟΙΑ - ΛΟΦΟΣ ΣΚΟΥΖΕ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΜΟΥΣΕΙΟ - ΑΚΑΔΗΜΙΑ - ΛΥΚΑΒΗΤΤΟΣ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΓΗΡΟΚΟΜΕΙΟ - ΑΡ.ΠΑΓΟΣ- ΔΙΚΑΣΤΗΡΙΑ ΕΥΕΛΠΙΔΩΝ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΠΛ. ΚΟΥΜΟΥΝΔΟΥΡΟΥ - ΚΟΛΩΝΑΚΙ - ΑΓΟΡΑ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΕΛΛΗΝΙΚΟ - ΑΛΙΜΟΣ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΑΓ. ΒΑΡΒΑΡΑ - ΣΤ. ΣΥΓΓΡΟΥ ΦΙΞ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΑΝΩ ΚΑΛΑΜΑΚΙ - ΣΤ. ΑΓ. ΔΗΜΗΤΡΙΟΣ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΑΓ. ΔΗΜΗΤΡΙΟΣ - ΣΤΑΘ. ΔΑΦΝΗΣ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΓΛΥΦΑΔΑ - ΚΑΒΟΥΡΙ - ΒΟΥΛΙΑΓΜΕΝΗ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΓΛΥΦΑΔΑ - ΒΟΥΛΙΑΓΜΕΝΗ - ΚΙΤΣΙ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΓΛΥΦΑΔΑ - ΒΑΡΗ - ΚΙΤΣΙ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΓΛΥΦΑΔΑ - ΒΑΡΗ (Πηγαδάκια) - ΠΡΟΑΣΤ. ΚΟΡΩΠΙΟΥ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΓΛΥΦΑΔΑ - ΑΓΙΑ ΤΡΙΑΔΑ - ΣΤ. ΕΛΛΗΝΙΚΟ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΣΤ. ΝΟΜΙΣΜΑΤΟΚΟΠΕΙΟ - ΠΑΙΑΝΙΑ - ΒΑΡΚΙΖΑ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΠΑΛ. ΦΑΛΗΡΟ - ΣΤ. ΣΥΓΓΡΟΥ ΦΙΞ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΓΛΥΦΑΔΑ - ΤΕΡΨΙΘΕΑ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΠΕΙΡΑΙΑΣ - Ν. ΣΜΥΡΝΗ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΣΤ. ΔΑΦΝΗΣ - ΑΜΑΞ/ΣΙΟ  ΑΓ. ΔΗΜΗΤΡΙΟΥ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΑΝΩ Ν. ΣΜΥΡΝΗ Β - ΣΤ. ΣΥΓΓΡΟΥ ΦΙΞ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΑΝΩ Ν. ΣΜΥΡΝΗ Α - ΣΤ. ΣΥΓΓΡΟΥ ΦΙΞ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΠΟΛΥΓΩΝΟ - ΓΛΥΦΑΔΑ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΣΤ. ΔΑΦΝΗΣ - ΚΑΛΑΜΑΚΙ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΣΤ. ΑΡΓΥΡΟΥΠΟΛΗ - ΚΑΛΑΜΑΚΙ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΓΛΥΦΑΔΑ - ΒΑΡΗ - ΒΑΡΚΙΖΑ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΣΤ. ΑΓ. ΔΗΜΗΤΡΙΟΣ - ΑΝΩ ΓΛΥΦΑΔΑ (ΠΑΝΟΡΑΜΑ ΒΟΥΛΑΣ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΕΛΛΗΝΙΚΟ - ΣΤ. ΑΛΙΜΟΣ - ΑΓΙΑ ΜΑΡΙΝΑ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΒΟΥΛΑ - ΠΑΝΟΡΑΜΑ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΒΟΥΛΑ - ΠΗΓΑΔΑΚΙΑ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΓΛΥΦΑΔΑ - ΒΑΡΚΙΖΑ - ΒΑΡΗ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΣΤ. ΜΕΤΡΟ ΕΛΛΗΝΙΚΟ - ΒΑΡΚΙΖΑ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΣΤΑΘ. ΔΑΦΝΗΣ - ΑΡΓΥΡΟΥΠΟΛΗ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΚΑΡΕΑΣ - ΑΚΑΔΗΜΙΑ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΣΤΡ. ΣΑΚΕΤΑ - ΑΚΑΔΗΜΙΑ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΓΛΥΦΑΔΑ - ΣΟΥΡΜΕΝΑ - ΤΕΡΨΙΘΕΑ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΑΓ. ΜΑΡΙΝΑ - ΣΤ. ΔΑΦΝΗΣ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΓΛΥΦΑΔΑ - ΤΕΡΨΙΘΕΑ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΜΕΤΑΜΟΡΦΩΣΗ - ΠΛΑΤΕΙΑ ΣΥΝΤΑΓΜΑΤΟΣ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΣΤ. ΜΕΤΡΟ ΔΑΦΝΗΣ - ΒΥΡΩΝΑΣ - ΚΑΡΕΑΣ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΠΕΙΡΑΙΑΣ - ΑΓ. ΔΗΜΗΤΡΙΟΣ (ΣΤΑΘ. ΔΑΦΝΗΣ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΠΕΙΡΑΙΑΣ - ΥΜΗΤΤΟΣ - ΗΛΙΟΥΠΟΛΗ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΣΤ. ΚΑΛΛΙΘΕΑΣ - ΑΓ. ΔΗΜΗΤΡΙΟΣ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΑΝΩ ΙΛΙΣΙΑ - ΑΚΑΔΗΜΙΑ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΠΑΝΕΠΙΣΤΗΜΙΟΥΠΟΛΗ - ΑΚΑΔΗΜΙΑ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΚΑΙΣΑΡΙΑΝΗ - ΕΛ. ΒΕΝΙΖΕΛΟΥ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΑΝΩ ΠΕΤΡΑΛΩΝΑ - ΑΓ. ΑΡΤΕΜΙΟΣ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΠΕΙΡΑΙΑΣ - ΑΓ. ΔΗΜΗΤΡΙΟΣ (ΣΤΑΘ. ΔΑΦΝΗΣ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΑΚΡΟΠΟΛΗ - ΖΩΓΡΑΦΟΥ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΠΕΙΡΑΙΑΣ - ΥΜΗΤΤΟΣ - ΒΥΡΩΝΑΣ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΖΩΓΡΑΦΟΥ - ΑΚΑΔΗΜΙΑ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΑΝΩ ΗΛΙΟΥΠΟΛΗ - ΣΤ. ΔΑΦΝΗΣ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΣΤ. ΚΑΤΕΧΑΚΗ - ΠΟΛΥΤΕΧΝΕΙΟΥΠΟΛΗ (ΚΥΚΛΙΚΗ) ΣΧΟΛ.', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΠΑΝΕΠΙΣΤΗΜΙΟΥΠΟΛΗ - ΣΤ. ΕΥΑΓΓΕΛΙΣΜΟΥ (ΚΥΚΛΙΚΗ) ΣΧ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΠΛ. ΚΑΡΑΪΣΚΑΚΗ - ΤΖΑΝΕΙΟ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΣΤ. ΔΟΥΚ. ΠΛΑΚΕΝΤΙΑΣ - ΑΝΘΟΥΣΑ - ΠΕΝΤΕΛΗ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΣΤ. ΔΟΥΚ. ΠΛΑΚΕΝΤΙΑΣ - ΑΝΘΟΥΣΑ - ΠΕΝΤΕΛΗ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΣΤΑΘΜΟΣ ΔΟΥΚ. ΠΛΑΚΕΝΤΙΑΣ - ΓΕΡΑΚΑ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΣΤ. ΝΟΜΙΣΜΑΤΟΚΟΠΕΙΟ - ΑΡΤΕΜΙΣ (ΒΡΑΥΡΩΝΑ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΣΤ. ΝΟΜΙΣΜΑΤΟΚΟΠΕΙΟ - ΑΡΤΕΜΙΣ (ΑΓ. ΝΙΚΟΛΑΟΣ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΣΤ. ΔΟΥΚ. ΠΛΑΚΕΝΤΙΑΣ - ΓΑΡΓΗΤΤΟΣ - ΓΕΡΑΚΑΣ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΣΤ. Δ. ΠΛΑΚΕΝΤΙΑΣ - ΓΛ. ΝΕΡΑ - ΠΡΟΑΣΤ.ΚΟΡΩΠΙΟΥ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΣΤ. ΝΟΜΙΣΜΑΤΟΚΟΠΕΙΟ - ΠΑΙΑΝΙΑ - ΚΟΡΩΠΙ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΚΟΡΩΠΙ - ΣΤ. ΠΡΟΑΣΤΙΑΚΟΥ - ΚΟΡΩΠΙ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΣΤ. ΔΟΥΚ. ΠΛΑΚΕΝΤΙΑΣ - ΝΟΜ. ΑΝ. ΑΤΤΙΚΗΣ - ΠΑΛΛΗΝΗ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΣΤ. ΝΟΜΙΣΜΑΤΟΚΟΠΕΙΟ - ΑΡΤΕΜΙΣ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΣΤ. ΜΕΤΡΟ ΔΟΥΚ. ΠΛΑΚ.- ΠΑΛΛΗΝΗ-ΕΚΠΤ. ΧΩΡΙΟ-ΣΠΑΤΑ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΑΓ. ΝΙΚΟΛΑΟΣ - ΒΡΑΥΡΩΝΑ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΒΡΑΥΡΩΝΑ - ΑΓ. ΝΙΚΟΛΑΟΣ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΑΝΘΟΥΣΑ - ΠΑΛΛΗΝΗ - ΚΑΝΤΖΑ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΚΟΡΩΠΙ - ΑΓ. ΜΑΡΙΝΑ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΣΤ. ΚΑΤΕΧΑΚΗ - ΠΟΛΥΔΡΟΣΟ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΣΤ. ΕΘΝ.ΑΜΥΝΑΣ - ΣΤ. ΧΑΛΑΝΔΡΙΟΥ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΣΤ. ΧΑΛΑΝΔΡΙ - ΜΕΛΙΣΣΙΑ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΣΤ. ΝΟΜΙΣΜ. - ΑΓ. ΠΑΡΑΣΚΕΥΗ - ΣΤ. ΠΛΑΚΕΝΤΙΑΣ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΣΤ. ΝΟΜΙΣΜΑΤΟΚΟΠΕΙΟ-ΝΕΑ ΖΩΗ - ΣΤ. ΔΟΥΚ. ΠΛΑΚΕΝΤΙΑΣ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΠΑΠΑΓΟΥ - ΣΤ. ΕΘΝ. ΑΜΥΝΑΣ-ΣΤ.ΚΑΤΕΧΑΚΗ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), ' Ο.Α.Κ.Α- ΑΝΩ ΜΕΛΙΣΣΙΑ  (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΣΤ. ΔΟΥΚ. ΠΛΑΚΕΝΤΙΑΣ - ΣΙΣΜΑΝΟΓΛΕΙΟ - ΧΑΛΑΝΔΡΙ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΠΑΠΑΓΟΥ - ΣΤ. ΚΑΤΕΧΑΚΗ - ΣΤ. ΕΘΝ. ΑΜΥΝΑΣ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΣΤ. ΕΘΝ. ΑΜΥΝΑΣ - ΧΟΛΑΡΓΟΣ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΣΤ. ΕΘΝ. ΑΜΥΝΑΣ - ΣΧΟΛ. ΧΟΛΑΡΓΟΥ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΠΕΙΡΑΙΑΣ - ΑΓ. ΑΝΑΡΓΥΡΟΙ (Μέσω ΚΗΦΙΣΟΥ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΑΓ. ΑΝΑΡΓΥΡΟΙ - ΑΓ. ΠΑΡΑΣΚΕΥΗ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΣΤ. ΧΑΛΑΝΔΡΙ - ΓΑΛΑΤΣΙ - ΣΤ. Α. ΠΑΤΗΣΙΩΝ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΣΤΑΘ. ΑΜΑΡΟΥΣΙΟΥ - ΝΟΣΟΚ. ΠΕΝΤΕΛΗΣ (Μέσω ΠΙΚΠΑ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΧΑΛΑΝΔΡΙ - ΑΝΩ ΒΡΙΛΗΣΣΙΑ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΣΤ. ΧΑΛΑΝΔΡΙ - ΧΑΛΑΝΔΡΙ - Ν. ΠΕΝΤΕΛΗ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΣΤ. ΧΑΛΑΝΔΡΙ - Ν. ΠΕΝΤΕΛΗ - ΧΑΛΑΝΔΡΙ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΣΤ. ΧΑΛΑΝΔΡΙ - ΧΑΛΑΝΔΡΙ - Π. ΠΕΝΤΕΛΗ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΣΤ. ΧΑΛΑΝΔΡΙ - Π. ΠΕΝΤΕΛΗ - ΧΑΛΑΝΔΡΙ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΠΕΥΚΗ - ΜΑΡΟΥΣΙ  Α (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΖΗΡΙΝΕΙΟ - ΒΑΡΥΜΠΟΜΠΗ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΘΡΑΚΟΜΑΚΕΔΟΝΕΣ - ΚΗΦΙΣΙΑ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΖΗΡΙΝΕΙΟ - ΡΟΔΟΠΟΛΗ - ΣΤΑΜΑΤΑ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΖΗΡΙΝΕΙΟ - ΑΓ. ΣΤΕΦΑΝΟΣ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΖΗΡΙΝΕΙΟ - ΚΡΥΟΝΕΡΙ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΣΤΑΘΜΟΣ ΚΗΦΙΣΙΑΣ - ΑΔΑΜΕΣ Α (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΣΤΑΘΜΟΣ ΚΗΦΙΣΙΑΣ - ΑΔΑΜΕΣ Β (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΣΤΑΘΜΟΣ ΚΗΦΙΣΙΑΣ - ΠΟΛΙΤΕΙΑ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΣΤ. ΚΗΦΙΣΙΑΣ - ΚΕΦΑΛΑΡΙ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΠΕΥΚΗ - ΜΑΡΟΥΣΙ Β (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΣΤΑΘΜΟΣ ΚΗΦΙΣΙΑΣ - ΜΕΛΙΣΣΙΑ - Ν. ΠΕΝΤΕΛΗ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΖΗΡΙΝΕΙΟ - ΕΥΞΕΙΝΟΣ ΠΟΝΤΟΣ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΖΗΡΙΝΕΙΟ - ΔΙΟΝΥΣΟΣ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΑΧΑΡΝΑΙ - ΒΑΡΥΜΠΟΜΠΗ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΜΕΤΑΜΟΡΦΩΣΗ - ΣΤΑΘ. ΑΜΑΡΟΥΣΙΟΥ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΣΤΑΘΜΟΣ ΚΗΦΙΣΙΑΣ - ΝΟΣΟΚ. ΑΓ. ΑΝΑΡΓΥΡΟΙ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'Π. ΦΑΛΗΡΟ - ΚΗΦΙΣΙΑ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΣΤΑΘΜΟΣ ΚΗΦΙΣΙΑΣ - ΜΟΡΤΕΡΟ - Ν. ΕΡΥΘΡΑΙΑ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'Ν. ΙΩΝΙΑ - ΚΑΛΟΓΡΕΖΑ - ΣΤΑΘ. ΠΑΝΟΡΜΟΥ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΝΟΣ. ΑΓ. ΑΝΑΡΓΥΡΩΝ - ΣΤ. ΜΕΤΑΜΟΡΦΩΣΗΣ - ΝΕΑ ΙΩΝΙΑ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΑΝΩ ΠΑΤΗΣΙΑ - ΠΕΡΙΣΣΟΣ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΓΑΛΑΤΣΙ - ΑΚΑΔΗΜΙΑ - ΝΕΚΡ. ΖΩΓΡΑΦΟΥ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΦΙΛΟΘΕΗ - ΑΜΠΕΛΟΚΗΠΟΙ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΓΟΥΔΗ - ΑΝΩ ΓΑΛΑΤΣΙ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΤΟΠΙΚΗ ΗΡΑΚΛΕΙΟΥ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΗΡΑΚΛΕΙΟ - ΑΓ.ΝΕΚΤΑΡΙΟΣ - ΠΕΥΚΗ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΨΥΧΙΚΟ - ΠΑΝΟΡΜΟΥ Α (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΨΥΧΙΚΟ - ΠΑΝΟΡΜΟΥ Β (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΑΓΙΑ ΤΡΙΑΔΑ ΠΕΤΡΟΥΠΟΛΗ - ΣΤ. ΑΓ. ΑΝΤΩΝΙΟΣ (ΚΥΚΛΙΚ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΚΑΜΑΤΕΡΟ - ΙΛΙΟΝ - ΣΤΑΘ. ΑΤΤΙΚΗΣ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΠΕΙΡΑΙΑΣ-ΑΓ. ΑΝΑΡΓΥΡΟΙ-ΑΓ. ΕΛΕΥΘΕΡΙΟΣ (Μέσω ΘΗΒΩΝ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΚΑΜΑΤΕΡΟ - ΣΤΑΘ. ΑΤΤΙΚΗΣ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΤΟΠΙΚΟ ΔΡΟΣΟΥΠΟΛΗΣ Α (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΖΩΦΡΙΑ - ΑΤΤΙΚΗ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΑΧΑΡΝΑΙ - ΕΡΓ. ΠΟΛΥΚΑΤΟΙΚΙΕΣ - Α.ΛΙΟΣΙΑ (ΠΑΝΟΡΑΜΑ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΚΗΠΟΥΠΟΛΗ - ΠΑΛΑΤΙΑΝΗ - ΣΤ. ΛΑΡΙΣΗΣ(ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΑΧΑΡΝΑΙ - ΚΗΦΙΣΙΑ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΦΥΛΗ - ΑΝΩ ΛΙΟΣΙΑ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΘΡΑΚ/ΔΟΝΕΣ - ΑΧΑΡΝΑΙ - Ν. ΙΩΝΙΑ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΑΧΑΡΝΑΙ - ΜΕΣΟΝΥΧΙ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΑΧΑΡΝΑΙ - ΠΛΑΤΩΝΑΣ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΑΧΑΡΝΑΙ - ΑΓ. ΚΩΝΣΤΑΝΤΙΝΟΣ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΛΟΦΟΣ ΑΞΙΩΜΑΤΙΚΩΝ - ΣΤ. ΑΓ. ΑΝΤΩΝΙΟΣ - ΖΩΟΔ. ΠΗΓΗ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΑΝΘΟΥΠΟΛΗ - ΣΤ. Μ. ΑΝΘΟΥΠΟΛΗ- ΑΤΤΙΚΟ ΝΟΣ-ΔΑΣΟΣ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΑΓ. ΦΑΝΟΥΡΙΟΣ - ΑΚΑΔΗΜΙΑ - ΖΩΟΔ. ΠΗΓΗ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΑΧΑΡΝΑΙ - ΑΜΑΞ. ΑΝΩ ΛΙΟΣΙΩΝ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΖΕΦΥΡΙ - ΣΤ. ΚΑΤΩ ΠΑΤΗΣΙΩΝ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΠΕΤΡΟΥΠΟΛΗ - ΠΑΝΟΡΑΜΑ - ΣΤΑΘ. ΑΤΤΙΚΗΣ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΧΡΥΣΟΥΠΟΛΗ-ΑΝΘΟΥΠΟΛΗ-ΣΤ.ΠΕΡΙΣΤΕΡΙ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΑΝΩ ΛΙΟΣΙΑ - ΟΙΚΙΣΜΟΣ ΓΕΝΝΗΜΑΤΑ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΑΤΤΙΚΟ ΝΟΣΟΚΟΜΕΙΟ - ΣΤ. ΜΕΤΡΟ ΑΙΓΑΛΕΩ - ΝΙΚΑΙΑ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΑΧΑΡΝΑΙ - ΑΓ. ΙΩΑΝΝΗΣ - ΑΓ. ΠΕΤΡΟΣ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΑΧΑΡΝΑΙ - ΑΓ. ΠΕΤΡΟΣ - ΑΓ. ΙΩΑΝΝΗΣ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΝΙΚΑΙΑ - ΠΕΙΡΑΙΑΣ (ΠΛ. ΑΝΑΛΗΨΕΩΣ) (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΠΕΙΡΑΙΑΣ - ΔΑΣΟΣ Β (Μέσω ΙΕΡΑΣ ΟΔΟΥ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΑΣΠΡΟΠΥΡΓΟΣ - ΝΕΟΚΤΙΣΤΑ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΚΟΡΥΔΑΛΛΟΣ - ΣΤ. ΜΕΤΡΟ ΑΙΓΑΛΕΩ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΑΝΩ ΚΟΡΥΔΑΛΛΟΣ - ΣΤ. ΜΕΤΡΟ ΑΙΓΑΛΕΩ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΣΧΙΣΤΟ - ΚΟΡΥΔΑΛΛΟΣ - ΠΕΙΡΑΙΑΣ Α (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΣΧΙΣΤΟ - ΚΟΡΥΔΑΛΛΟΣ - ΠΕΙΡΑΙΑΣ Β (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΧΑΪΔΑΡΙ - ΣΤ. ΜΕΤΡΟ ΑΙΓΑΛΕΩ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΑΒΕΡΩΦ - ΠΡΟΥΣΣΗΣ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΣΧΙΣΤΟ - ΚΑΡΑΒΑΣ - ΠΕΙΡΑΙΑΣ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΓΟΥΔΗ - ΤΑΥΡΟΣ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΤΑΥΡΟΣ - ΑΓ. ΔΗΜΗΤΡΙΟΣ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΕΛΕΥΣΙΝΑ - ΜΑΝΔΡΑ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΛΙΜ. ΠΕΡΑΜΑΤΟΣ - ΑΝΩ ΠΕΡΑΜΑ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΠΕΡΑΜΑ - ΝΕΚΡ. ΣΧΙΣΤΟΥ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΚΕΡΑΤΣΙΝΙ - ΣΤ. ΜΕΤΡΟ ΑΙΓΑΛΕΩ (ΤΟΠΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΑΓΙΑ ΑΝΑΣΤΑΣΙΑ - ΣΤ. ΑΓ. ΑΝΤΩΝΙΟΣ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΣΤ. ΑΓ. ΑΝΤΩΝΙΟΣ - ΝΕΑ ΖΩΗ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΑΓ. ΒΑΣΙΛΕΙΟΣ - ΣΤ. ΑΓ. ΑΝΤΩΝΙΟΣ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΑΓ. ΑΝΤΩΝΙΟΣ Α - ΠΕΙΡΑΙΑΣ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΑΓ. ΑΝΤΩΝΙΟΣ Β - ΠΕΙΡΑΙΑΣ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΠΕΙΡΑΙΑΣ - ΑΓ. ΜΗΝΑΣ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΠΕΙΡΑΙΑΣ - Γ΄ ΝΕΚΡΟΤ. - ΑΣΠΡΑ ΧΩΜΑΤΑ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΠΕΙΡΑΙΑΣ - ΑΣΠΡΑ ΧΩΜΑΤΑ - Γ΄ ΝΕΚΡΟΤ. (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'Τ.Ε.Ι  ΑΘΗΝΑΣ-ΣΤ.ΜΕΤΡΟ ΑΙΓΑΛΕΩ-Τ.Ε.Ι. ΠΕΙΡΑΙΑ (ΚΥΚ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΠΕΙΡΑΙΑΣ - ΑΓ. ΒΑΡΒΑΡΑ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΠΕΙΡΑΙΑΣ - ΑΙΓΑΛΕΩ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΠΕΙΡΑΙΑΣ - ΕΥΓΕΝΕΙΑ - ΧΑΡΑΥΓΗ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΠΕΙΡΑΙΑΣ - ΧΑΡΑΥΓΗ - ΕΥΓΕΝΕΙΑ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΑΓΙΑ ΒΑΡΒΑΡΑ - ΣΤ. ΜΕΤΡΟ ΑΙΓΑΛΕΩ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΟΜΟΝΟΙΑ - ΡΕΝΤΗΣ - ΠΑΛ. ΚΟΚΚΙΝΙΑ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΠΕΙΡΑΙΑΣ - ΠΕΡΑΜΑ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΠΕΙΡΑΙΑΣ - ΕΛΕΥΣΙΝΑ (Μέσω ΘΗΒΩΝ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΝΕΑΠΟΛΗ - ΠΕΙΡΑΙΑΣ Α (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΝΕΑΠΟΛΗ - ΠΕΙΡΑΙΑΣ Β (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΝΕΑΠΟΛΗ - ΧΑΡΑΥΓΗ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΝΕΑΠΟΛΗ - ΣΤ. ΜΕΤΡΟ ΑΙΓΑΛΕΩ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΨΑΡΙ - ΑΣΠΡΟΠΥΡΓΟΣ - ΛΟΦΟΣ ΚΥΡΙΛΛΟΥ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΑΙΓΑΛΕΩ - ΥΜΗΤΤΟΣ - ΔΑΦΝΗ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΠΕΙΡΑΙΑΣ - ΔΕΞΑΜΕΝΕΣ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'Π. ΦΑΛΗΡΟ-ΓΕΝ. ΚΡΑΤΙΚΟ ΝΙΚΑΙΑΣ-ΣΧΙΣΤΟ ΚΕΡΑΤΣΙΝΙΟΥ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΠΑΡΑΛΙΑ - ΑΝΩ ΕΛΕΥΣΙΝΑ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΕΛΕΥΣΙΝΑ - ΘΡΙΑΣΙΟ ΝΟΣ. - ΜΑΝΔΡΑ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΕΛΕΥΣΙΝΑ - ΒΙΟΜΗΧΑΝΙΚΗ ΖΩΝΗ ΜΑΓΟΥΛΑΣ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΠΛ. ΚΟΥΜΟΥΝΔΟΥΡΟΥ - ΜΑΝΔΡΑ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΑΣΠΡΟΠΥΡΓΟΣ - ΣΤ. ΜΕΤΡΟ ΑΙΓΑΛΕΩ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΠΕΙΡΑΙΑΣ - ΕΛΕΥΣΙΝΑ (Μέσω Λ. ΣΧΙΣΤΟΥ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΠΕΙΡΑΙΑΣ - Ν. ΜΩΛΟΣ ΔΡΑΠΕΤΣΩΝΑΣ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΑΧΑΡΝΑΙ - ΕΛΕΥΣΙΝΑ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΑΧΑΡΝΑΙ - ΘΡΙΑΣΙΟ ΝΟΣΟΚΟΜΕΙΟ - ΕΛΕΥΣΙΝΑ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΕΛΕΥΣΙΝΑ - ΑΣΠΡΟΠΥΡΓΟΣ - ΡΟΥΠΑΚΙ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΑΙΓΑΛΕΩ - ΠΕΡΙΣΤΕΡΙ - ΣΤΑΘ. ΑΤΤΙΚΗΣ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΑΓ. ΒΑΡΒΑΡΑ - ΧΑΪΔΑΡΙ - ΑΓ. ΑΝΑΡΓΥΡΟΙ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΠΛ. ΚΑΡΑΪΣΚΑΚΗ - ΣΤ. ΠΕΙΡΑΙΑ - ΦΡΕΑΤΤΥΔΑ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΠΛ. ΚΑΡΑΪΣΚΑΚΗ - ΚΑΛΛΙΠΟΛΗ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΑΓ. ΒΑΣΙΛΕΙΟΣ - ΑΓ. ΣΟΦΙΑ - ΚΡΑΤ. ΝΙΚΑΙΑΣ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΣΤ. ΣΥΓΓΡΟΥ ΦΙΞ - ΤΖΙΤΖΙΦΙΕΣ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΣΤΑΘ. ΚΑΛΛΙΘΕΑΣ - ΙΔΡ. ΤΥΦΛΩΝ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΟΜΟΝΟΙΑ - ΛΑΧΑΝΑΓΟΡΑ - ΠΑΛ. ΚΟΚΚΙΝΙΑ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΛΟΦΟΣ ΒΩΚΟΥ- ΠΡ.ΗΛΙΑΣ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΠΕΙΡΑΙΑΣ - ΒΟΥΛΑ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΣΤΑΘΜΟΣ ΛΑΡΙΣΗΣ - ΑΧΑΡΝΑΙ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΠΛ. ΒΑΘΗ - ΙΛΙΟΝ - ΠΕΤΡΟΥΠΟΛΗ (ΜΕΣΩ ΠΑΝΟΡΑΜΑΤΟΣ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΟΜΟΝΟΙΑ - ΚΗΠΟΥΠΟΛΗ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΣΤ. ΛΑΡΙΣΗΣ - ΔΑΣΟΣ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΠΛ. ΚΟΥΜΟΥΝΔΟΥΡΟΥ - ΕΛΕΥΣΙΝΑ (Μέσω ΙΕΡΑΣ ΟΔΟΥ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΑΚΑΔΗΜΙΑ - ΒΟΥΛΑ (Μέσω Λ. ΑΜΦΙΘΕΑΣ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΑΚΑΔΗΜΙΑ - ΓΛΥΦΑΔΑ (ΕΥΡΥΑΛΗ) (Μέσω ΒΟΥΛΙΑΓΜΕΝΗΣ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΑΚΑΔΗΜΙΑ - ΚΑΤΩ ΗΛΙΟΥΠΟΛΗ - ΤΕΡΨΙΘΕΑ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΑΚΑΔΗΜΙΑ - ΑΓ. ΠΑΡΑΣΚΕΥΗ - ΑΝΘΟΥΣΑ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΣΤΟΥΡΝΑΡΗ - ΚΗΦΙΣΙΑ (ΠΛ.ΠΛΑΤΑΝΟΥ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΠΟΛΥΤΕΧΝΕΙΟ - Ν. ΙΩΝΙΑ - ΜΑΡΟΥΣΙ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΠΕΙΡΑΙΑΣ - ΑΝΩ ΓΛΥΦΑΔΑ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΣΤΑΘΜΟΣ ΛΑΡΙΣΗΣ - ΑΧΑΡΝΑΙ (Μέσω ΑΡΙΣΤΟΤΕΛΟΥΣ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΠΛ. ΒΑΘΗ - ΙΛΙΟΝ - ΠΕΤΡΟΥΠΟΛΗ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΜΑΡΝΗ - ΑΝΩ ΛΙΟΣΙΑ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΣΤ. ΛΑΡΙΣΗΣ - ΠΑΛΑΤΑΚΙ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΠΛ. ΚΟΥΜΟΥΝΔΟΥΡΟΥ - ΕΛΕΥΣΙΝΑ (Μέσω  Λ. ΑΘΗΝΩΝ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΟΜΟΝΟΙΑ - ΠΕΡΑΜΑ (Μέσω Π. ΡΑΛΛΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΑΚΑΔΗΜΙΑ - ΑΓΙΟΣ ΚΟΣΜΑΣ (Μέσω ΠΑΡΑΛΙΑΚΗΣ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΑΚΑΔΗΜΙΑ-ΓΛΥΦΑΔΑ(ΚΑΡΑΧΑΛΙΟΥ)(Μέσω Λ.ΒΟΥΛΙΑΓΜΕΝΗΣ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΣΤ. ΛΑΡΙΣΗΣ - Λ. ΑΛΕΞΑΝΔΡΑΣ - ΑΓ. ΠΑΡΑΣΚΕΥΗ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΠΟΛΥΤΕΧΝΕΙΟ - Ν. ΦΙΛΑΔΕΛΦΕΙΑ - ΜΕΤΑΜΟΡΦΩΣΗ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΧΑΛΚΟΚΟΝΔΥΛΗ - ΜΕΤΑΜΟΡΦΩΣΗ - Ν. ΚΗΦΙΣΙΑ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΑΝΑΚΑΣΑ - ΑΓ. ΑΝΑΡΓΥΡΟΙ - ΠΛ. ΒΑΘΗ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΚΑΜΑΤΕΡΟ - ΑΓ.ΝΙΚΟΛΑΟΣ-ΙΛΙΟΝ - ΠΟΛ/ΧΝΕΙΟ(ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΠΛ. ΚΟΥΜΟΥΝΔΟΥΡΟΥ - ΑΣΠΡΟΠΥΡΓΟΣ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΟΜΟΝΟΙΑ - ΠΕΡΑΜΑ (Μέσω ΓΡ. ΛΑΜΠΡΑΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΧΑΛΚΟΚΟΝΔΥΛΗ - Κ. ΜΥΛΟΣ - ΑΧΑΡΝΑΙ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΣΥΝΤΑΓΜΑ - Ο.Α.Κ.Α - ΥΠ.ΠΑΙΔΕΙΑΣ (EXPRESS)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΣΤ. ΛΑΡΙΣΗΣ - ΤΕΙ ΑΘΗΝΩΝ (ΣΧΟΛΙΚΗ  EXPRESS)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΣΤ. ΜΕΤΡΟ ΕΛΛΗΝΙΚΟ - ΣΑΡΩΝΙΔΑ (ΕΧPRESS)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΠΕΙΡΑΙΑΣ - ΠΑΝΕΠΙΣΤΗΜΙΟΥΠΟΛΗ (ΣΧΟΛΙΚΗ EXPRESS)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΣΥΝΤΑΓΜΑ - ΚΗΦΙΣΙΑ', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΜΑΝΔΡΑ - ΟΙΚ. ΤΙΤΑΝ - ΣΤ. ΜΕΤΡΟ ΑΙΓΑΛΕΩ (ΚΥΚΛΙΚΗ)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΣΤ. ΥΠΕΡ. ΛΕΩΦ. ΚΗΦΙΣΟΥ - ΑΕΡ/ΝΑΣ ΑΘΗΝΩΝ (EXPRESS)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΣΥΝΤΑΓΜΑ - ΑΕΡΟΛ. ΑΘΗΝΩΝ (EXPRESS)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΠΕΙΡΑΙΑΣ - ΑΕΡΟΛ. ΑΘΗΝΩΝ (EXPRESS)', now(), now());
insert into bus_routes values (nextval('bus_routes_id_seq'), 'ΣΤ. ΜΕΤΡΟ ΕΛΛΗΝΙΚΟ - ΑΕΡΟΛ. ΑΘΗΝΩΝ (EXPRESS)', now(), now());
";
  end
end
